import { useState } from 'react'
import { useGame } from '../state/game'
import { backend } from '../services/backend'
export function Report() {
  const { session, action, busy } = useGame()
  const [answers, setAnswers] = useState<Record<string, string>>({ operator: '', credential: '', location: '', archive: '' })
  if (!session) return null
  const ready = session.completedPuzzles.length === session.puzzles.length
  return <section className="report"><div className="eyebrow">CASE 047 / INVESTIGATOR FINDINGS</div><h2>Make the evidence speak.</h2><p>Identify the operator—not merely the account named in the access log. Corroborate your report using the physical packet and signed device record.</p><p className="caution">{5 - session.attempts} final submissions remaining. An incorrect report does not identify which answer failed.</p>{!ready && <p className="muted">Filing is restricted until the terminal reviews and archive custody check are complete.</p>}<form onSubmit={e => { e.preventDefault(); void action(() => backend.submit(answers), 'Investigation accepted.') }}>{[['operator', 'Who operated the recovered adapter?'], ['credential', 'Which credential was compromised?'], ['location', 'Where did the physical activity occur?'], ['archive', 'What archive object was accessed?']].map(([key, label]) => <label key={key}>{label}<input required maxLength={120} value={answers[key]} onChange={e => setAnswers({ ...answers, [key]: e.target.value })} autoComplete="off" /></label>)}<button className="primary" disabled={!ready || busy}>Submit investigation →</button></form></section>
}
export function Hints() {
  const { session, action, busy } = useGame()
  return <section className="terminal-copy"><div className="eyebrow">SUPERVISOR ASSISTANCE</div><h2>A second pair of eyes.</h2><p>Three requests per investigation. Guidance responds to your current review and becomes more explicit with each request. Every use is logged for the Game Master; no time penalty is applied in this version.</p><ol className="hint-list">{session?.hints.map((hint, i) => <li key={i}>{hint}</li>)}</ol><button disabled={busy || (session?.hints.length ?? 0) >= 3} onClick={() => void action(() => backend.hint(), 'Supervisor guidance received.')}>Request guidance · {session?.hints.length ?? 0}/3 used</button></section>
}
export function Settings({ resume }: { resume: () => void }) {
  const { volume, sensitivity, quality, settings, action, session } = useGame()
  const [restart, setRestart] = useState(false)
  return <section className="settings"><div className="eyebrow">FIELD OPERATIONS / SETTINGS</div><h2>Investigation paused.</h2><p className="caution">The server clock continues while this menu is open.</p><div className="control-grid"><p><kbd>W A S D</kbd> / arrow keys<br />Move through the facility</p><p><kbd>Mouse</kbd><br />Look around</p><p><kbd>E</kbd><br />Inspect the object under your crosshair</p><p><kbd>I</kbd> / <kbd>Tab</kbd><br />Open the case file</p><p><kbd>H</kbd><br />Request assistance</p><p><kbd>Esc</kbd><br />Release mouse / settings</p></div><label>Room ambience · {Math.round(volume * 100)}%<input type="range" min="0" max="1" step=".01" value={volume} onChange={e => settings({ volume: +e.target.value })} /></label><label>Mouse sensitivity · {sensitivity.toFixed(1)}<input type="range" min=".3" max="2" step=".1" value={sensitivity} onChange={e => settings({ sensitivity: +e.target.value })} /></label><label className="checkbox"><input type="checkbox" checked={quality} onChange={e => settings({ quality: e.target.checked })} /> Enhanced shadows & antialiasing (faster laptops)</label><button className="primary" onClick={resume}>Return to facility →</button><hr />{restart ? <div><p>Start a separate practice session? The old session remains in the server audit. Notes will be cleared.</p><button onClick={() => void action(() => backend.create(session?.team ?? 'Practice')).then(ok => { if (ok) { settings({ notes: '' }); window.location.reload() } })}>Confirm new practice session</button><button onClick={() => setRestart(false)}>Cancel</button></div> : <button className="text-button" onClick={() => setRestart(true)}>Restart as a new practice session</button>}</section>
}
