import { chromium, expect } from '@playwright/test'
const browser = await chromium.launch({ channel: 'msedge', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', error => errors.push(error.message))
try {
  await page.goto('http://127.0.0.1:3001')
  await expect(page.getByRole('heading', { name: 'Someone was here. The record remains.' })).toBeVisible()
  await page.screenshot({ path: 'smoke.png' })
  await page.getByLabel('Investigation team').fill('Browser QA')
  await page.getByRole('button', { name: 'Enter facility' }).click()
  await expect(page.getByRole('heading', { name: 'Follow the evidence.' })).toBeVisible()
  await expect(page.locator('canvas')).toBeVisible()
  const session = await page.evaluate(async () => (await fetch('/api/session')).json())
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Follow the evidence.' })).toBeVisible()
  const resumed = await page.evaluate(async () => (await fetch('/api/session')).json())
  expect(resumed.id).toBe(session.id); expect(resumed.deadline).toBe(session.deadline)
  await page.getByRole('button', { name: 'Case file' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByText('No preserved records yet.')).toBeVisible()
  await page.getByRole('button', { name: 'Close panel' }).click()
  await page.getByRole('button', { name: 'Hints 0/3' }).click()
  await page.getByRole('button', { name: 'Request guidance' }).click()
  await expect(page.locator('.hint-list li')).toHaveCount(1)
  await page.getByRole('button', { name: 'Close panel' }).click()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(page.getByLabel('Room ambience')).toBeVisible()
  expect(errors).toEqual([])
  console.log('PASS: briefing → session → 3D canvas → refresh persistence → case file → server hint → settings. No page errors.')
} finally { await browser.close() }
